In [2]:
import numpy as np


In [3]:
a = np.array([[4,2,3],[1,3,5]])
print(a.size) # size is the number of elemnts in the matrix so basically number of rows times the number of columns

a.tolist() # returns the matrix in list notation basically
# so the way you would pass an argument to numpy.array()

# np.info(a) # whole lot of info about the numpy array a 
# np.info(a.tolist) # whole documentation of ndarray.tolist()
# np.info(np.array) # doc of numpy.array function


6


[[4, 2, 3], [1, 3, 5]]

In [4]:
#when copying references do get copied therefore use copy functions 

b = a.copy() #instead of b = a 

a.sort()
a.flatten() # flattens 2D to 1D

a.T ###property not a function
# np.delete(a,0,axis=0) delete 0th row(axis=0) of a


array([[2, 1],
       [3, 3],
       [4, 5]])

In [17]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

np.sum(c,axis=1)

np.insert(c,[0,1,2],1,axis=0)

array([[ 1,  1,  1],
       [ 1,  2,  3],
       [ 1,  1,  1],
       [ 4,  5,  6],
       [ 1,  1,  1],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
d = np.array([[1,2,3]])
e = np.array([[4,5,6]])

# np.concatenate((d,e),axis=1)
d/e

array([[0.25, 0.4 , 0.5 ]])